#This are the language settings from MySQL.
#You can customize every single message and add custom colors via § prefix.
#You must not create / edit / remove words in capital letters that already exist or are not from yourself
#You must not add custom colors or special characters, etc. to config setup messages.
Messages:
  ConfigMessages:
    ConfigSetupDatabaseName: "Enter your database name here"
    ConfigSetupDatabasePort: "Enter your database port here"
    ConfigSetupDatabaseHost: "Enter your database host here"
    ConfigSetupUsername: "Enter your username here"
    ConfigSetupPassword: "Enter your password here"
    ConfigSetupConfigurationNotSetError: "§cMySQL Configuration not set. Please enter your data in: PACKAGELOCATION  and reload the server."
    ConfigDeleted: "§cAll values of the MySQL config have been deleted."
    ConfigPathDeleted: "§cThe value of the MySQL config path CONFIGPATH has been deleted."
    ConfigDeletionErrorAllowClearConfigFalse: "§cDeleting the MySQL config is not possible, allowClearConfig is false."
    ConfigPathDeletionErrorAllowClearConfigFalse: "§cDeleting the MySQL config path is not possible, allowClearConfig is false."
    ConfigMySQlNotSavedInError: "§cThis MySQL database is not stored via a config."
  MySQLConnected: "§aThe connection to the database has been established."
  MySQLConnectionError: "§cConnection to database failed."
  MySQLDisconnected: "§cThe connection to the database has been disconnected."
  MySQLReconnected: "§aMySQL was successfully reconnected."
